version: 2
jobs:
  build_and_deploy:
    docker:
      - image: verdigristech/ci-base
    working_directory: ~/docker-ci-scala
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Cloud
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t verdigristech/ci-scala .
      - run:
          name: Deploy container
          command: docker push verdigristech/ci-scala

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
